[package]
name = "sing-box-windows"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0.6", features = ["tray-icon", "unstable"] }
tauri-plugin-log = "2.0.0-rc"
reqwest = { version = "0.12.9", features = ["json", "stream", "rustls-tls"] }
winreg = "0.10.1"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
futures-util = "0.3"
zip = { version = "0.5.13" }
lazy_static = "1.4.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-window-state = "2"
